name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'
        
        - name: Set up Playwright
  uses: playwright-action/setup-playwright@v1

         run: ls -l ~/.cache/ms-playwright/
   - name: List installed Playwright browsers

    - name: Install dependencies
      run: npm install

    - name: Clear Playwright cache
      run: rm -rf ~/.cache/ms-playwright

    - name: Install Playwright browsers
      run: npx playwright install --with-deps

    - name: Run Playwright tests
      run: npx playwright test

      - name: Verify Playwright browsers
        run: |
    echo "Checking installed browsers..."
    ls -l ~/.cache/ms-playwright/

   
 

      
